### ISSUE TITLE
Error when executing make

### ISSUE THREAD

**Issue by dalareo** [Edraak/edx-docker-devstack#2]
I get:

```
Could not open requirements file: [Errno 2] No such file or directory: 'requirements/edx/github.txt'
make: *** [lms_install_github_prereqs] Error 1
```

**Comment by OmarIthawi** [comment]
Thanks for testing it. Will check and let you know about it.

**Comment by dalareo** [comment]
I am building a Container As A Service platform with Rancher and I am very interested in solving edX deploying inside a container. Official deployment is not very friendly! ;)))

**Comment by OmarIthawi** [comment]
@dalareo I've created #3 to fix the issue with a basic TravisCI to ensure that the basic build passes.

**Comment by OmarIthawi** [comment]
BTW I agree with you that the official deployment is not docker-friendly. There has been multiple attempts to solve the problem.

However, I don't know about Rancher, please let me know how it works with the edX platform.
