### ISSUE TITLE
Errors building with make

### ISSUE THREAD

**Issue by dalareo** [Edraak/edx-docker-devstack#6]
studio_1    | 
lms_1       | Build failed running pavelib.servers.lms: Subprocess return code: 1
studio_1    | Build failed running pavelib.servers.studio: Subprocess return code: 1
mysql_1     | InnoDB: 127 rollback segment(s) active.
mysql_1     | InnoDB: Creating foreign key constraint system tables
mysql_1     | InnoDB: Foreign key constraint system tables created
mysql_1     | 151221 20:23:12  InnoDB: Waiting for the background threads to start
mysql_1     | MySQL init process in progress...
edxdockerdevstack_lms_1 exited with code 1
mysql_1     | 151221 20:23:13 InnoDB: 5.5.47 started; log sequence number 0
mysql_1     | 151221 20:23:13 [Warning] 'user' entry 'root@e13d5920bb2b' ignored in --skip-name-resolve mode.
edxdockerdevstack_studio_1 exited with code 1
mysql_1     | 151221 20:23:13 [Warning] 'user' entry '@e13d5920bb2b' ignored in --skip-name-resolve mode.
mysql_1     | 151221 20:23:13 [Warning] 'proxies_priv' entry '@ root@e13d5920bb2b' ignored in --skip-name-resolve mode.
mysql_1     | 151221 20:23:13 [Note] Event Scheduler: Loaded 0 events
mysql_1     | 151221 20:23:13 [Note] mysqld: ready for connections.
mysql_1     | Version: '5.5.47'  socket: '/tmp/mysql.sock'  port: 0  MySQL Community Server (GPL)
mysql_1     | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql_1     | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
mysql_1     | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql_1     | 151221 20:23:15 [Warning] 'proxies_priv' entry '@ root@e13d5920bb2b' ignored in --skip-name-resolve mode.
mysql_1     | 
mysql_1     | 151221 20:23:15 [Note] mysqld: Normal shutdown
mysql_1     | 
mysql_1     | 151221 20:23:15 [Note] Event Scheduler: Purging the queue. 0 events
mysql_1     | 151221 20:23:15  InnoDB: Starting shutdown...
mysql_1     | /entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
mysql_1     | 
mysql_1     | 151221 20:23:16  InnoDB: Shutdown completed; log sequence number 1595675
mysql_1     | 151221 20:23:16 [Note] mysqld: Shutdown complete
mysql_1     | 
mysql_1     | 151221 20:23:16 [Note] mysqld (mysqld 5.5.47) starting as process 1 ...
mysql_1     | 151221 20:23:16 [Note] Plugin 'FEDERATED' is disabled.
mysql_1     | 151221 20:23:16 InnoDB: The InnoDB memory heap is disabled
mysql_1     | 151221 20:23:16 InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1     | 151221 20:23:16 InnoDB: Compressed tables use zlib 1.2.3
mysql_1     | 151221 20:23:16 InnoDB: Using Linux native AIO
mysql_1     | 151221 20:23:17 InnoDB: Initializing buffer pool, size = 128.0M
mysql_1     | 151221 20:23:17 InnoDB: Completed initialization of buffer pool
mysql_1     | 151221 20:23:17 InnoDB: highest supported file format is Barracuda.
mysql_1     | 
mysql_1     | MySQL init process done. Ready for start up.
mysql_1     | 
mysql_1     | 151221 20:23:17  InnoDB: Waiting for the background threads to start
mysql_1     | 151221 20:23:18 InnoDB: 5.5.47 started; log sequence number 1595675
mysql_1     | 151221 20:23:18 [Note] Server hostname (bind-address): '0.0.0.0'; port: 3306
mysql_1     | 151221 20:23:18 [Note]   - '0.0.0.0' resolves to '0.0.0.0';
mysql_1     | 151221 20:23:18 [Note] Server socket created on IP: '0.0.0.0'.
mysql_1     | 151221 20:23:18 [Warning] 'proxies_priv' entry '@ root@e13d5920bb2b' ignored in --skip-name-resolve mode.
mysql_1     | 151221 20:23:18 [Note] Event Scheduler: Loaded 0 events
mysql_1     | 151221 20:23:18 [Note] mysqld: ready for connections.
mysql_1     | Version: '5.5.47'  socket: '/tmp/mysql.sock'  port: 3306  MySQL Community Server (GPL)
nginx_1     | nginx: [emerg] host not found in upstream "lms" in /etc/nginx/sites-enabled/edxapp:10
edxdockerdevstack_nginx_1 exited with code 1

**Comment by OmarIthawi** [comment]
It is strange that I am unable to reproduce this on my machine, could you please provide me with more details about the environment:
- Linux version/distro
- Kernel version
- docker/compose versions

Thanks

**Comment by dalareo** [comment]
I am using Packet.net bare metal server with:

Docker 1.9.1
Docker Compose 1.5.2
Linux Kernel 3.13.0-73-generic
Ubuntu 14.04

**Comment by OmarIthawi** [comment]
@dalareo Thanks, I'll see how can I reproduce the error.

**Comment by dalareo** [comment]
I was able to build it. But now...

I just get NGINX welcome page!!! ;)

**Comment by OmarIthawi** [comment]
That's good, try to open:
- www.local.edx.org
- studio.local.edx.org

**Comment by OmarIthawi** [comment]
Please let me know if you've had any updates @dalareo
